---
title: "Return Analysis"
author: "Mingze Li"
date: "2015-04-16"
output:
  pdf_document:
    latex_engine: xelatex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(traveltimeCLT)
library(data.table)
# setwd("D:/李明泽/留学/Statistics Master/travel pricing/R-simulation/")
```

```{r}
trips <- fread("data/trips.csv")
trips$timeBin <- time_bins_readable(trips$time)
start_end <- trips[
  , .(
    start = linkId[order(time)][1],
    end = linkId[order(time)[.N]],
    start_time = time[order(time)][1],
    distance = sum(length)
  ), trip
]

# start_end[, sorted_pair := fcase(
#   start < end, paste(start, end, sep = "->"),
#   start > end, paste(end, start, sep = "->")
# )]

# pair_counts <- start_end[, .(count = .N), by = sorted_pair][order(-count)]
pair_counts <- start_end[, .(count = .N, start_time = max(start_time)), by = .(start, end)][order(-count)]
```

```{r}
# hyperparameters of the simulation.
set.seed(1234)
# repeat time: how many times to repeat the simulation.
repeat_time <- 10
# X: how many trips to simulate for each real trip.
X <- 5
# significance level: how similar the new edges are to the old edges.
# a larger value means less similar, a smaller value means more similar.
significance_level <- 0.05
# sigma_n: the standard deviation of the noise added to the number of edges.
sigma_n <- 2
# trip_num: the number of trips to simulate.
trip_num <- 30
```

```{r}
simulated_data <- data.table(
  repeat_time = rep(1:repeat_time, each = ceiling(trip_num / X))
)
groups <- pair_counts[count >= ceiling(trip_num / X), ]
simulated_data <- simulated_data[,
  {
    group <- groups[sample.int(nrow(groups), 1)]
    trip_set <- start_end[(start == group$start & end == group$end)]
    id <- sample.int(nrow(trip_set), ceiling(trip_num / X))
    .(
      trip = trip_set$trip[id],
      start_time = trip_set$start_time[id]
    )
  },
  by = repeat_time
]
simulated_test <- similar_route(simulated_data$trip, trips, r = X, sigma_n = sigma_n, significance = significance_level)
simulated_price <- similar_route(simulated_data$trip, trips, r = X, sigma_n = sigma_n, significance = significance_level)

simulated_price <- merge(simulated_price, simulated_data[, c("trip", "start_time")], by = "trip")
setnames(simulated_price, old = c("newtrip", "linkId", "length", "start_time"), new = c("tripID", "linkID", "distance_meters", "entry_time"), skip_absent = TRUE)
simulated_test <- merge(simulated_test, simulated_data[, c("trip", "start_time")], by = "trip")
setnames(simulated_test, old = c("newtrip", "linkId", "length", "start_time"), new = c("tripID", "linkID", "distance_meters", "entry_time"), skip_absent = TRUE)
```

```{r}
# find all R and K in the trips set
names(trips)[c(2, 3, 5, 7, 8)] <- c("tripID", "entry_time", "duration_secs", "distance_meters", "linkID")
trips_stat <- trips[, .(
  real_price = price(max(entry_time) - min(entry_time), sum(distance_meters))[, 1]
), tripID]
trips$speed <- exp(trips$logspeed)
fit <- traveltimeCLT(trips, "trip-specific")
```

```{r}
fit_price <- predict(fit, simulated_price)
fit_test <- predict(fit, simulated_test)
price_stat <- simulated_price[, .(
  start_time = min(entry_time),
  distance = sum(distance_meters)
), tripID]
price_stat$R <- request_R(fit_price, price_stat$start_time, price_stat$start_time, price_stat$distance, K = 0.9, risk_free = 0, zeta = 0)
price_stat$K <- request_K(fit_price, price_stat$distance, discount_factor = 0.9)

test_stat <- simulated_test[, .(
  start_time = min(entry_time),
  distance = sum(distance_meters)
), tripID]
test_stat$R <- request_R(fit_test, test_stat$start_time, test_stat$start_time, test_stat$distance, K = 0.9, risk_free = 0, zeta = 0)
test_stat$K <- request_K(fit_test, test_stat$distance, discount_factor = 0.9)
```

```{r}
test_time <- simulated_test[, .(
  duration = sum(exp(mean + qnorm(dependent_uniform(.N, 0.31)) * sd)),
  distance = sum(distance_meters)
), tripID]
test_time$price <- price(test_time$duration, test_time$distance)[, 1]
revenue <- sum(price_stat$R) / trip_num / repeat_time
revenue
profit <- price_stat$R - pmax(test_time$price - price_stat$K, 0)
```
```{r}
mean(profit)
var(profit)
max(profit)
min(profit)
length(profit[profit > 0]) / length(profit)
```

```{r}
setnames(trips, old = c("tripID", "linkID", "distance_meters", "entry_time"), new = c("trip", "linkId", "length", "time"), skip_absent = TRUE)
timeBin_x_edge <- get_timeBin_x_edges(trips)
i <- which(profit == min(profit)) - 0
profit[i]
price_stat[i, ]
test_time[i, "duration"]
edge <- simulated_test[simulated_test$tripID == test_stat[i, tripID], ]
template <- na.omit(trips[trip == edge$trip[1], ])
setnames(template, old = c("linkID"), new = c("linkId"), skip_absent = TRUE)
template <- merge(template[, c("linkId", "timeBin")], timeBin_x_edge, by = c("linkId", "timeBin"))
edge
edge[, .(
  duration = sum(exp(mean + qnorm(dependent_uniform(.N, 0.31)) * sd)),
  expection = sum(exp(mean)),
  noise = sum(sd)
), tripID]
template[, .(
  duration = sum(exp(mean + qnorm(dependent_uniform(.N, 0.31)) * sd)),
  expection = sum(exp(mean)),
  noise = sum(sd)
)]
```