---
title: "Table 3"
author: "Mingze Li"
date: "2015-06-18"
output:
  pdf_document:
    latex_engine: xelatex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(traveltimeCLT)
library(data.table)
```

```{r}
trips <- fread("data/trips.csv")
trips2 <- fread("data/trips.csv")
names(trips)[c(2, 3, 5, 7, 8)] <- c("tripID", "entry_time", "duration_secs", "distance_meters", "linkID")
trips$speed <- exp(trips$logspeed)
trips$timeBin <- time_bins_readable(trips$entry_time)
set.seed(1234)
id <- sample(unique(trips$trip), 2000)
test_id <- sample(id, 40)
train_id <- setdiff(id, test_id)
user_records <- subset(trips, tripID %in% train_id)
test_records <- subset(trips, tripID %in% test_id)
study_records <- subset(trips, !tripID %in% test_id)
trips2 <- subset(trips2, !trip %in% test_id)
```

```{r}
user_records[, time_category := ifelse(timeBin %in% c("MorningRush", "EveningRush"), timeBin, "Otherwise")]
test_records[, time_category := ifelse(timeBin %in% c("MorningRush", "EveningRush"), timeBin, "Otherwise")]

user_data <- user_records[, .(
    start_time = min(entry_time),
    end_time = max(entry_time),
    duration = sum(duration_secs),
    distance = sum(distance_meters)
), by = tripID]
user_data$real_price <- price(user_data$duration, user_data$distance)[, 1]
test_data <- test_records[, .(
    start_time = min(entry_time),
    end_time = max(entry_time),
    duration = sum(duration_secs),
    distance = sum(distance_meters)
), by = tripID]
test_data$real_price <- price(test_data$duration, test_data$distance)[, 1]
```

```{r}
simulated_record <- similar_route(train_id, trips2, sigma_n = 2, significance = 0.6)
names(simulated_record)[c(2, 3, 8)] <- c("tripID", "linkID", "distance_meters")
simulated_record$entry_time <- simulated_record[
    ,
    entry_time := as.POSIXct(rep(runif(1, min = min(user_data$start_time), max = max(user_data$start_time)), .N)),
    tripID
]
simulated_data <- simulated_record[, .(
    distance = sum(distance_meters),
    start_time = min(entry_time)
), by = tripID]
multipler <- 49 / 1000
```

```
multipler <- 5 # indicate how many times the simulation should be repeated
My <- rbinom(30 * multipler, 2, 2 / 3)
bk <- sample(c("MorningRush", "EveningRush", "Otherwise"), sum(My) * 10, replace = TRUE)
rho_k <- user_records[.(bk = bk),
    on = .(time_category = bk),
    .(sample(unique(tripID), 1, replace = TRUE)),
    by = .EACHI
]$V1
temp_dt <- data.table(tripID = rho_k, i = seq_along(rho_k))
simulated_record <- user_records[temp_dt,
    on = .(tripID),
    nomatch = 0,
    allow.cartesian = TRUE
]
rm(temp_dt)
simulated_data <- simulated_record[, .(
    tripID = rep(tripID[1], 100),
    distance = rep(sum(distance_meters))
), by = i]
simulated_data$start_time <- as.POSIXct(runif(nrow(simulated_data), min = min(user_data$start_time), max = max(user_data$start_time)))
```


```{r}
fit1 <- traveltimeCLT(trips, "trip-specific")
fit2 <- traveltimeCLT(trips, "population")
p1 <- predict(fit1, simulated_record)
p2 <- predict(fit2, simulated_record)
p1 <- data.table(p1)
p2 <- data.table(p2)
p1 <- merge(p1, simulated_data, by = c("tripID"), all.y = TRUE)
p2 <- merge(p2, simulated_data, by = c("tripID"), all.y = TRUE)
p1 <- na.omit(p1)
p2 <- na.omit(p2)
```

```{r}
Rt_0 <- request_R(p1, p1$start_time, p1$start_time, p1$distance, risk_free = 0, zeta = 0)
Rp_0 <- request_R(p2, p2$start_time, p2$start_time, p2$distance, risk_free = 0, zeta = 0)
Rt_1 <- request_R(p1, p1$start_time, p1$start_time, p1$distance, risk_free = 0, zeta = 0.1)
Rp_1 <- request_R(p2, p2$start_time, p2$start_time, p2$distance, risk_free = 0, zeta = 0.1)
Kt <- request_K(p1, p1$start_time, p1$start_time, p1$distance, risk_free = 0)
Kp <- request_K(p2, p2$start_time, p2$start_time, p2$distance, risk_free = 0)
```
```{r}
group_mean <- function(x, group_size) {
    dt <- data.table(x)
    names(dt) <- "value"
    dt[, chunk := (seq_len(.N) - 1) %/% group_size]
    Kt_sum_dt <- dt[, .(mean_value = sum(value) / group_size), by = chunk]$mean_value
    return(Kt_sum_dt)
}
group_max <- function(x, group_size) {
    dt <- data.table(x)
    names(dt) <- "value"
    dt[, chunk := (seq_len(.N) - 1) %/% group_size]
    Kt_sum_dt <- dt[, .(max_value = max(value)), by = chunk]$max_value
    return(Kt_sum_dt)
}
```


```{r}
Rt_0 <- mean(group_mean(Rt_0, 1000 * multipler))
Rt_1 <- mean(group_mean(Rt_1, 1000 * multipler))
Rp_0 <- mean(group_mean(Rp_0, 1000 * multipler))
Rp_1 <- mean(group_mean(Rp_1, 1000 * multipler))
Kt <- mean(group_max(Kt, 1000 * multipler))
Kp <- mean(group_max(Kp, 1000 * multipler))
P <- test_data$real_price
```
```{r}
profit_t_0 <- (Rt_0 + pmin(Kt - P, 0))
profit_t_1 <- (Rt_1 + pmin(Kt - P, 0))
profit_p_0 <- (Rp_0 + pmin(Kp - P, 0))
profit_p_1 <- (Rp_1 + pmin(Kp - P, 0))
```

```{r}
Model <- c(rep("Trip-Specific", 2), rep("Population", 2))
Cutoff <- rep(c(0, 0.1), 2)
Percentage_profit <- c(
    mean(profit_t_0 / P * 100),
    mean(profit_t_1 / P * 100),
    mean(profit_p_0 / P * 100),
    mean(profit_p_1 / P * 100)
)
Average_profit <- c(
    mean(profit_t_0),
    mean(profit_t_1),
    mean(profit_p_0),
    mean(profit_p_1)
)
Maximum_Loss <- c(
    min(profit_t_0),
    min(profit_t_1),
    min(profit_p_0),
    min(profit_p_1)
)
```

```{r}
table3 <- data.table(
    Model = Model,
    Cutoff = Cutoff,
    Percentage_Profit = round(Percentage_profit, 5),
    Average_Profit = round(Average_profit, 5),
    Maximum_Loss = round(Maximum_Loss, 5)
)
table3
```

```{r}
positive <- 0
negative <- 0
for (i in 1:1000) {
    if (mean(pmin(rnorm(10000, 1), 0.105)) > 0) {
        positive <- positive + 1
    } else {
        negative <- negative + 1
    }
}
positive
negative
```