---
title: "Table 4"
author: "Mingze Li"
date: "2015-07-02"
output:
  pdf_document:
    latex_engine: xelatex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(traveltimeCLT)
library(data.table)
```

```{r}
test_size <- 40 # number of trips for test set
trips <- fread("data/trips.csv")
trips2 <- fread("data/trips.csv")
names(trips)[c(2, 3, 5, 7, 8)] <- c("tripID", "entry_time", "duration_secs", "distance_meters", "linkID")
trips$speed <- exp(trips$logspeed)
trips$timeBin <- time_bins_readable(trips$entry_time)
set.seed(1234)
id <- sample(unique(trips$trip), test_size * 50)
test_id <- sample(id, test_size)
train_id <- setdiff(id, test_id)
user_records <- subset(trips, tripID %in% train_id)
test_records <- subset(trips, tripID %in% test_id)
study_records <- subset(trips, !tripID %in% test_id)
```

```{r}
user_records[, time_category := ifelse(timeBin %in% c("MorningRush", "EveningRush"), timeBin, "Otherwise")]
test_records[, time_category := ifelse(timeBin %in% c("MorningRush", "EveningRush"), timeBin, "Otherwise")]

user_data <- user_records[, .(
    start_time = min(entry_time),
    end_time = max(entry_time),
    duration = sum(duration_secs),
    distance = sum(distance_meters)
), by = tripID]
user_data$real_price <- price(user_data$duration, user_data$distance)[, 1]
test_data <- test_records[, .(
    start_time = min(entry_time),
    end_time = max(entry_time),
    duration = sum(duration_secs),
    distance = sum(distance_meters)
), by = tripID]

test_data$real_price <- price(test_data$duration, test_data$distance)[, 1]
```
```{r}
rider <- 1:100
M <- seq(0, floor(test_size * 0.5), floor(test_size * 0.1))
quantile <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
# produce data table with M and quantile as groups, and every group contains all riders
pressure_data <- data.table(
    M = rep(M, each = length(quantile) * max(rider)),
    quantile = rep(quantile, each = max(rider)),
    rider = rep(rider, length(M) * length(quantile))
)
# for each row, repeat it for test_size times
pressure_data <- pressure_data[, .(
    i = seq(1, test_size, 1)
), by = .(M, quantile, rider)]
# sample from test_data with replacement, the distance limited from quantile to 1.
sampled_data <- pressure_data[,
    {
        q_value <- quantile(test_data$distance, probs = quantile)
        abuse_trips <- test_data[distance >= q_value]
        abuse_sample <- abuse_trips[sample(1:nrow(abuse_trips), size = M, replace = TRUE)]
        normal_sample <- test_data[sample(1:nrow(test_data), size = test_size - M, replace = TRUE)]
        sampled <- rbind(abuse_sample, normal_sample)
        cbind(.SD, sampled)
    },
    by = .(quantile, rider, M)
]
# View(sampled_data[,
#     .(price = mean(real_price)),
#    by =.(quantile, M)
# ])
```

```{r}
multipler <- 1 # indicate how many times the simulation should be repeated
My <- test_size * multipler
bk <- sample(c("MorningRush", "EveningRush", "Otherwise"), sum(My) * 10, replace = TRUE)
rho_k <- user_records[.(bk = bk),
    on = .(time_category = bk),
    .(rep(sample(unique(tripID), 1, replace = TRUE), 10)),
    by = .EACHI
]$V1
temp_dt <- data.table(tripID = rho_k, i = seq_along(rho_k))
simulated_record <- user_records[temp_dt,
    on = .(tripID),
    nomatch = 0,
    allow.cartesian = TRUE
]
rm(temp_dt)
names(simulated_record)[c(2, ncol(simulated_record))] <- c("trip", "tripID")
start_time <- runif(max(simulated_record$tripID), min = min(test_data$start_time), max = max(test_data$start_time))
start_time <- as.POSIXct(start_time)
simulated_record$entry_time <- start_time[simulated_record$tripID]
simulated_data <- simulated_record[, .(
    trip = unique(trip),
    start_time = min(entry_time),
    distance = sum(distance_meters),
    duration = sum(duration_secs)
), by = tripID]
```


```{r}
fit1 <- traveltimeCLT(trips, "trip-specific")
fit2 <- traveltimeCLT(trips, "population")
p1 <- predict(fit1, simulated_record)
p2 <- predict(fit2, simulated_record)
p1 <- data.table(p1)
p2 <- data.table(p2)
p1 <- merge(p1, simulated_data, by = c("tripID"), all.y = TRUE)
p2 <- merge(p2, simulated_data, by = c("tripID"), all.y = TRUE)
```

```{r}
group_mean <- function(x, group_size) {
    dt <- data.table(x)
    names(dt) <- "value"
    dt[, chunk := (seq_len(.N) - 1) %/% group_size]
    Kt_sum_dt <- dt[, .(mean_value = sum(value) / group_size), by = chunk]$mean_value
    return(Kt_sum_dt)
}
group_max <- function(x, group_size) {
    dt <- data.table(x)
    names(dt) <- "value"
    dt[, chunk := (seq_len(.N) - 1) %/% group_size]
    Kt_sum_dt <- dt[, .(max_value = max(value)), by = chunk]$max_value
    return(Kt_sum_dt)
}
```

```{r}
Rt_0 <- request_R(p1, p1$start_time, p1$start_time, p1$distance, risk_free = 0, zeta = 0)
Rp_0 <- request_R(p2, p2$start_time, p2$start_time, p2$distance, risk_free = 0, zeta = 0)
Kt <- request_K(p1, p1$distance)
Kp <- request_K(p2, p2$distance)
Rt_0 <- na.omit(Rt_0)
Rt_0 <- mean(group_max(Rt_0, 100 * multipler)) * 1

Kt <- mean(group_max(Kt, 100 * multipler)) * 1
profit <- sampled_data[, .(
    profit = Rt_0 * test_size + sum(pmin(Kt - real_price, 0)),
    expand = sum((real_price))
), by = .(M, quantile, rider)]
cost_stats_table <- profit[, .(
    pct_mean = mean((profit) / expand * test_size, na.rm = TRUE),
    variance = var(profit) / sqrt(test_size),
    dollar_mean = mean(profit, na.rm = TRUE)
), by = .(M, quantile)]
# table(sampled_data$real_price)
```


```{r}
# reshape the data to draw the table
table4 <- dcast(cost_stats_table, M ~ quantile, value.var = "pct_mean")
table5 <- dcast(cost_stats_table, M ~ quantile, value.var = "variance")
table6 <- dcast(cost_stats_table, M ~ quantile, value.var = "dollar_mean")
table4
table5
table6
```

